### ISSUE TITLE
Yet Another Slim Application Error

### ISSUE THREAD

**Issue by Gartral** [AzuraCast/AzuraRelay#19]
I updated azuracast and I'm getting Slim Application Error on the web panel. 

`docker-compose logs -f web` shows this, over and over: 

`azuracast_web              | PHP Fatal error:  Uncaught DI\NotFoundException: No entry or class found for 'App\Locale' in /var/azuracast/www/vendor/php-di/php-di/src/Container.php:194
azuracast_web              | Stack trace:
azuracast_web              | #0 /var/azuracast/www/src/AppFactory.php(39): DI\Container->make()
azuracast_web              | #1 /var/azuracast/www/bin/console(11): App\AppFactory::createCli()
azuracast_web              | #2 {main}
azuracast_web              |   thrown in /var/azuracast/www/vendor/php-di/php-di/src/Container.php on line 194
azuracast_web              | 
azuracast_web              | Fatal error: Uncaught DI\NotFoundException: No entry or class found for 'App\Locale' in /var/azuracast/www/vendor/php-di/php-di/src/Container.php:194
azuracast_web              | Stack trace:
azuracast_web              | #0 /var/azuracast/www/src/AppFactory.php(39): DI\Container->make()
azuracast_web              | #1 /var/azuracast/www/bin/console(11): App\AppFactory::createCli()
azuracast_web              | #2 {main}
azuracast_web              |   thrown in /var/azuracast/www/vendor/php-di/php-di/src/Container.php on line 194
azuracast_web              | [2021-03-29T02:58:32.236301+00:00] AzuraCast.CRITICAL: Fatal error: Uncaught DI\NotFoundException: No entry or class found for 'App\Locale' in /var/azuracast/www/vendor/php-di/php-di/src/Container.
php:194 Stack trace: #0 /var/azuracast/www/src/AppFactory.php(39): DI\Container->make() #1 /var/azuracast/www/bin/console(11): App\AppFactory::createCli() #2 {main}   thrown in /var/azuracast/www/vendor/php-di/php-di/src/Conta
iner.php on line 194 [] []`

**Comment by SlvrEagle23** [comment]
Closing as very likely fixed in subsequent rolling releases.
