### ISSUE TITLE
Where to fill in the Azuracast instance information

### ISSUE THREAD

**Issue by griffon56** [AzuraCast/AzuraRelay#3]
Hi,

I am trying to setup a AzuraRelay as I understand it is a front server program that retrieves and exposes all my Azuracast radios on a single Icecast instance.

After launch it I get following error message :

`[ERROR] Base URL or API key is not specified. Please supply these values in "azurarelay.env" to continue!.
`
My questions are : 
1) where to fill in these informations in the /var/nginx/azurarelay.env file ?
2) is it possible to run azurarelay to connect to azuracast hosted on a different server ?

Many thanks for your hard work

**Comment by Vaalyn** [comment]
Did the `./docker.sh install` prompt you for the API key with the following text?

```
AzuraCast API Key
You must provide an API key for an authorized account on this installation.
You can generate a new API key at: xxx
AzuraCast API Key:
```

> is it possible to run azurarelay to connect to azuracast hosted on a different server ?

Yes that's the intended use-case, running the relay on one or many other servers to scale up your listener capacity.

**Comment by griffon56** [comment]
Thanks Vaalyn, I used a ready-made azurarelay container from this repository https://hub.docker.com/r/azuracast/azurarelay. So I was not asked for the API

Question :
Is it possible to run a single instance of icecast to relay several azuracast radios ?I need to use just one port on my server for the listeners to access all radios.

Thanks,
Antoine

**Comment by Vaalyn** [comment]
Could you clarify how you installed the relay?
I'm not sure if you have followed the installation instructions for the relay or not.

**Comment by griffon56** [comment]
I installed the docker image on my Synology NAS, so there was no CLI installation. I did not run the docker.sh as indicated in the installation steps.
Could you answer my above question please ?

**Comment by Vaalyn** [comment]
Here you can see what the setup is writing to the environment file: https://github.com/AzuraCast/AzuraRelay/blob/master/www/src/Console/Command/SetupCommand.php#L124
