### ISSUE TITLE
Problem: Azurarelay Icecast Client Count Limited to 2500

### ISSUE THREAD

**Issue by opeoniye** [AzuraCast/AzuraRelay#30]
This issue has been around for a while and i don't know if it is intentional or an error. I found out using the Azurarelay docker image that the icecast clients counts in the config for each station in **/var/azurarelay/stations** is limited to **2500**.
I manually update this file by copying it from the relay container, modifying it, copy it back and then restart the container but this method is temporal and it soon gets overwritten with the default values, hence prompting me to perform the modification every time.
How can you guys help us fix this?
<img width="899" alt="Screenshot 2021-11-29 at 3 26 41 PM" src="https://user-images.githubusercontent.com/6058136/143885846-58597b02-9506-48e1-8df6-f1ce9382cfc1.png">

Thanks

**Comment by vneznaikin** [comment]
a github search for the keyword "2500" found one match
https://github.com/AzuraCast/AzuraRelay/blob/d22240a98c31fb88ef43685bcd7a35f52085e239/www/src/Console/Command/UpdateCommand.php

```
 protected function writeStationConfiguration(
        AdminRelayDto $relay,
        string $baseDir,
        string $baseUrl
    ): string {
        $configPath = $baseDir.'/'.$relay->getShortcode().'.xml';

        $config = [
            'location' => 'AzuraCast',
            'admin' => 'icemaster@localhost',
            'hostname' => 'localhost',
            'limits' => [
                'clients' => 2500,
                'sources' => count($relay->getMounts()),
                'queue-size' => 524288,
                'client-timeout' => 30,
                'header-timeout' => 15,
                'source-timeout' => 10,
                'burst-size' => 65535,
            ],
```
I have not studied how it works. just information

I guess the problem is in the poor documentation?

**Comment by SC2Mitch** [comment]
I suppose we could bump the number up, or allow a user to configure it without playing around with the files. 

What listener count do you think is suitable?

**Comment by vneznaikin** [comment]
this is https://icecast.org/loadtest/ official icecast  tests
`Well, we know that it can definitely handle 14000 concurrent users given a similarly sized hardware configuration. We all conclude that icecast itself can handle even more concurrent users, with the main limitation most likely being the network interface.`

further, the number of connections depends on the server architecture. judging by the docker file, nginx is used as a proxy. Hence nginx will be the next bottleneck. here we need to test whether the nginx configuration is appropriate for high-load systems.

In general, as you can see from the icecast test results, the "client limits" must be specified based on the bandwidth of your server !!!

@opeoniye @SC2Mitch You can confirm that the AzuraRelay interface not have the ability to overwrite Icecast configuration (AzuraCast does)

**Comment by opeoniye** [comment]
@vneznaikin Thanks so much for your discovery. I've made some changed to the Azurarelay code based on your findings and created a docker image from it for my own use.
