### ISSUE TITLE
[ERROR] No relayable streams were found on Azuracast 0.15.0 server

### ISSUE THREAD

**Issue by RS232DZ** [AzuraCast/AzuraRelay#33]
Hi,
I have this error when I try to connect Azurarelay to the last stable version of Azuracast (0.15.0)
"[ERROR] No relayable streams were found on the remote server. Make sure your account has permission to "Manage Broadcasting" for the station you want to relay."
The account exist and have the permission to "Manage Broadcasting" of the station but azurarelay can't find it.
The previous stable version (0.14.1) is working fine.
PS: Redirecting from old /api_keys issue was resolve in the [last commit](https://github.com/AzuraCast/AzuraCast/commit/787020593df70b0335fb1e352d3b3590fe2f9bed) of Azuracast

**Comment by SlvrEagle23** [comment]
@RS232DZ On my test installations, I'm not having this same issue. This may be something specific to your setup, or something that's changed between 0.14 and 0.15 as far as default settings go that we're not using in our test setup.

**Comment by RS232DZ** [comment]
Updated my running 0.14 to 0.15 and it works
Thanks @SlvrEagle23
