### ISSUE TITLE
Could not connect to supervisord.

### ISSUE THREAD

**Issue by D3aDM0r0Se** [AzuraCast/AzuraRelay#37]
Hello, I have a problem with AzuraRelay on vps ubuntu 20.04.3

 [OK] Setup is complete!

[+] Running 6/6
 ⠿ Container azurarelay_relay          Removed                                                                                                                                                                                          1.5s
 ⠿ Volume azurarelay_station_data      Removed                                                                                                                                                                                          0.0s
 ⠿ Network azurarelay_frontend         Removed                                                                                                                                                                                          0.1s
 ⠿ Volume azurarelay_letsencrypt       Removed                                                                                                                                                                                          0.0s
 ⠿ Volume azurarelay_letsencrypt_acme  Removed                                                                                                                                                                                          0.0s
 ⠿ Volume azurarelay_tmp_data          Removed                                                                                                                                                                                          0.0s
[+] Running 6/6
 ⠿ Network azurarelay_frontend           Created                                                                                                                                                                                        0.1s
 ⠿ Volume "azurarelay_tmp_data"          Created                                                                                                                                                                                        0.0s
 ⠿ Volume "azurarelay_station_data"      Created                                                                                                                                                                                        0.0s
 ⠿ Volume "azurarelay_letsencrypt"       Created                                                                                                                                                                                        0.0s
 ⠿ Volume "azurarelay_letsencrypt_acme"  Created                                                                                                                                                                                        0.0s
 ⠿ Container azurarelay_relay            Started                                                                                                                                                                                        1.2s
[2022-02-14T00:23:50.215612+00:00] AzuraRelay.ERROR: RuntimeException: Could not connect to supervisord. (uncaught exception) at /var/azurarelay/www_tmp/CompiledContainer.php line 128 while running console command `Unknown` {"exception":"[object] (RuntimeException(code: 0): Could not connect to supervisord. at /var/azurarelay/www_tmp/CompiledContainer.php:128)"} []

In CompiledContainer.php line 128:

  Could not connect to supervisord.

**Comment by leakim69** [comment]
I have the same problem. Tried it on both DigitalOcean and Linode, get the exact same as above.

**Comment by julianborghuis** [comment]
Same...

**Comment by SlvrEagle23** [comment]
This should be significantly improved in the latest Rolling update.
