### ISSUE TITLE
relay bitrate and format is not displayed

### ISSUE THREAD

**Issue by ahmadabdolsaheb** [AzuraCast/AzuraRelay#4]
Hi everyone,

I am currently using https://coderadioadmin.freecodecamp.org/api/nowplaying_static/coderadio.json 
for pulling metadata.

 For some reason the bit rate is not specified for remote mounts (relays). 
Would it be possible to get those in?

![image](https://user-images.githubusercontent.com/4591597/62688195-0bdf5580-b9d1-11e9-9deb-2f458407de9a.png)

Thank you

**Comment by SlvrEagle23** [comment]
This was fixed in an updated release of AzuraCast.
