### ISSUE TITLE
cannot install azurarelay on fresh ubuntu server 

### ISSUE THREAD

**Issue by marekdziem** [AzuraCast/AzuraRelay#47]
Hi Marek here from www.eclipse-streaming.co.za

calling #BusterNeece and #Vaalyn !! (via Maak :) )

What a great project! 
I have run into an issue trying to install Azura relay ;)

much frustration....why does a legitimate azuracast URL not function!? 
It's a digital oceans droplet container and I've tried the IP address as well!

https://eclipse-radio.eclipse-streaming.co.za/api/nowplaying returns happy JSON for parsing when opened directly/

no ways I had to wait 3000ms for the installer to break - its instant.
please help!

AzuraRelay Setup
================
Welcome to AzuraRelay! Provide the following items to finish setup.
AzuraCast Installation URL
--------------------------
AzuraRelay has to connect to a "parent" AzuraCast instance to relay its broadcast(s).
Provide the base URL of that installation (including "http://" or "https://") to continue.

 AzuraCast Installation URL []:
 > https://eclipse-radio.eclipse-streaming.co.za

[2022-10-16T23:13:42.283720+00:00] AzuraRelay.ERROR: HTTP client GET call to https://eclipse-radio.eclipse-streaming.co.za/api/nowplaying produced response NULL [] []

 [ERROR] Could not connect to AzuraCast instance at https://eclipse-radio.eclipse-streaming.co.za: cURL error
         28: Connection timed out after 3000 milliseconds (see
         https://curl.haxx.se/libcurl/c/libcurl-errors.html) for
         https://eclipse-radio.eclipse-streaming.co.za/api/nowplaying
         /var/azurarelay/www/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php L210: #0
         /var/azurarelay/www/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(158):
         GuzzleHttp\Handler\CurlFactory::createRejection()
         #1 /var/azurarelay/www/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(110):
         GuzzleHttp\Handler\CurlFactory::finishError()
         #2 /var/azurarelay/www/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47):
         GuzzleHttp\Handler\CurlFactory::finish()
         #3 /var/azurarelay/www/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28):
         GuzzleHttp\Handler\CurlHandler->__invoke()
         #4 /var/azurarelay/www/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(48):
         GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}()
         #5 /var/azurarelay/www/vendor/guzzlehttp/guzzle/src/Middleware.php(201):
         GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}()
         #6 /var/azurarelay/www/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(35):
         GuzzleHttp\Middleware::GuzzleHttp\{closure}()
         #7 /var/azurarelay/www/vendor/guzzlehttp/guzzle/src/Middleware.php(31):
         GuzzleHttp\PrepareBodyMiddleware->__invoke()
         #8 /var/azurarelay/www/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(71):
         GuzzleHttp\Middleware::GuzzleHttp\{closure}()
         #9 /var/azurarelay/www/vendor/guzzlehttp/guzzle/src/Middleware.php(61):
         GuzzleHttp\RedirectMiddleware->__invoke()
         #10 /var/azurarelay/www_tmp/CompiledContainer.php(26): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
         #11 /var/azurarelay/www/vendor/guzzlehttp/guzzle/src/HandlerStack.php(75):
         CompiledContainer::{closure}()
         #12 /var/azurarelay/www/vendor/guzzlehttp/guzzle/src/Client.php(331):
         GuzzleHttp\HandlerStack->__invoke()
         #13 /var/azurarelay/www/vendor/guzzlehttp/guzzle/src/Client.php(168): GuzzleHttp\Client->transfer()
         #14 /var/azurarelay/www/vendor/guzzlehttp/guzzle/src/Client.php(187):
         GuzzleHttp\Client->requestAsync()
         #15 /var/azurarelay/www/vendor/azuracast/php-api-client/src/AbstractClient.php(54):
         GuzzleHttp\Client->request()
         #16 /var/azurarelay/www/vendor/azuracast/php-api-client/src/Client.php(24):
         AzuraCast\Api\AbstractClient->request()
         #17 /var/azurarelay/www/src/Console/Command/SetupCommand.php(48): AzuraCast\Api\Client->nowPlaying()
         #18 /var/azurarelay/www/vendor/symfony/console/Helper/QuestionHelper.php(467):
         App\Console\Command\SetupCommand->App\Console\Command\{closure}()
         #19 /var/azurarelay/www/vendor/symfony/console/Helper/QuestionHelper.php(74):
         Symfony\Component\Console\Helper\QuestionHelper->validateAttempts()
         #20 /var/azurarelay/www/vendor/symfony/console/Style/SymfonyStyle.php(348):
         Symfony\Component\Console\Helper\QuestionHelper->ask()
         #21 /var/azurarelay/www/src/Console/Command/SetupCommand.php(62):
         Symfony\Component\Console\Style\SymfonyStyle->askQuestion()
         #22 /var/azurarelay/www/vendor/symfony/console/Command/Command.php(291):
         App\Console\Command\SetupCommand->execute()
         #23 /var/azurarelay/www/vendor/symfony/console/Application.php(1007):
         Symfony\Component\Console\Command\Command->run()
         #24 /var/azurarelay/www/vendor/symfony/console/Application.php(299):
         Symfony\Component\Console\Application->doRunCommand()
         #25 /var/azurarelay/www/vendor/symfony/console/Application.php(171):
         Symfony\Component\Console\Application->doRun()
         #26 /var/azurarelay/www/bin/console(11): Symfony\Component\Console\Application->run()
         #27 {main}

 AzuraCast Installation URL []:
 >

**Comment by maaakmal** [comment]
Following also got stuck
Thanks
M

**Comment by marekdziem** [comment]
I' managed to install without problem once I had all ports open on public IP
