### ISSUE TITLE
Azurarelay Install  Failure

### ISSUE THREAD

**Issue by N4444VX** [AzuraCast/AzuraRelay#48]
I am getting stuck during install with the following errors. I reverted the azuracast.docker.scarf.sh back to ghcr.io just for giggles but it still didn't work. Any ideas?

**Ubuntu 18.04.6 LTS
Docker version 20.10.20, build 9fdeb9c
docker-compose version 1.25.3, build d4d1b42b**

```
ERROR: Invalid interpolation format for "relay" option in service "services": "azuracast.docker.scarf.sh/azuracast/relay:${AZURARELAY_VERSION:-latest}"
Error: No such container:path: azurarelay_relay:/var/app/www_tmp/azurarelay.env

```

**Comment by BusterNeece** [comment]
@N4444VX Likely you need to update Docker Compose. You can run `./docker.sh install-docker-compose` to do so.
