### ISSUE TITLE
Error after installing

### ISSUE THREAD

**Issue by miguelacjardim** [AzuraCast/AzuraRelay#5]
i'm getting this error after installing AzuraRelay using docker

Error:

**Fatal error: Uncaught Error: Call to undefined method Azura\App::create() in /var/azurarelay/www/web/index.php:7 Stack trace: #0 {main} thrown in /var/azurarelay/www/web/index.php on line 7**

this error is showing on the browser and console.

any idea to solve.
thank you

**Comment by SlvrEagle23** [comment]
@miguelacjardim @eranwo This should be fixed as of a few moments ago. Please update and let me know if it resolves the issue.

**Comment by eranwo** [comment]
Now it works fine. Thanks!
