### ISSUE TITLE
i have a error when a try to install AzuraRelay

### ISSUE THREAD

**Issue by oyeandres** [AzuraCast/AzuraRelay#8]
Hi im trying to install azurarelay but when add the url of the azuracast installation. i see this error...

`AzuraRelay Setup
================

Welcome to AzuraRelay! Provide the following items to finish setup.

AzuraCast Installation URL
--------------------------

AzuraRelay has to connect to a "parent" AzuraCast instance to relay its broadcast(s).
Provide the base URL of that installation (including "http://" or "https://") to continue.

 AzuraCast Installation URL []:
 > https://cdn.digitalradio.mx
[16-Mar-2020 14:20:18 UTC] PHP Fatal error:  Uncaught TypeError: Argument 5 passed to AzuraCast\Api\Dto\MountDto::__construct() must be of the type int, null given, called in /var/azurarelay/www/vendor/azuracast/php-api-client/src/Dto/MountDto.php on line 201 and defined in /var/azurarelay/www/vendor/azuracast/php-api-client/src/Dto/MountDto.php:46
Stack trace:
#0 /var/azurarelay/www/vendor/azuracast/php-api-client/src/Dto/MountDto.php(201): AzuraCast\Api\Dto\MountDto->__construct()
#1 /var/azurarelay/www/vendor/azuracast/php-api-client/src/Dto/StationDto.php(303): AzuraCast\Api\Dto\MountDto::fromArray()
#2 /var/azurarelay/www/vendor/azuracast/php-api-client/src/Dto/NowPlayingDto.php(195): AzuraCast\Api\Dto\StationDto::fromArray()
#3 /var/azurarelay/www/vendor/azuracast/php-api-client/src/Client.php(28): AzuraCast\Api\Dto\NowPlayingDto::fromArray()
#4 /var/azurarelay/www/src/Console/Command/SetupCommand.php(35): AzuraCast\Api\Client->nowPlaying()
#5 /var/azurarelay/www/vendor/symfony/console/Helper/QuestionHelper.php(451): App\Console\Command\SetupComma in /var/azurarelay/www/vendor/azuracast/php-api-client/src/Dto/MountDto.php on line 46
Error: No such container:path: azurarelay_relay_1:/var/azurarelay/www_tmp/azurarelay.env
Stopping azurarelay_relay_1 ... done
Removing azurarelay_relay_1 ... done
Removing network azurarelay_default
Removing volume azurarelay_letsencrypt
Removing volume azurarelay_station_data
Removing volume azurarelay_tmp_data
Creating network "azurarelay_default" with the default driver
Creating volume "azurarelay_letsencrypt" with default driver
Creating volume "azurarelay_station_data" with default driver
Creating volume "azurarelay_tmp_data" with default driver
Creating azurarelay_relay_1 ... done

AzuraRelay Updater
==================

                                                                                                                        
 [ERROR] Base URL or API key is not specified. Please supply these values in "azurarelay.env" to continue!.             
                                                                                                                        

root@ubuntu-s-1vcpu-2gb-sfo2-01:/var/azurarelay# `

can you help me please?

**Comment by zezekim** [comment]
I have the same issue when trying to reinstall my relay. 
It used to work on the old version before the changes 22 days ago.

**Comment by oyeandres** [comment]
Could you solve the problem?

**Comment by SlvrEagle23** [comment]
@oyeandres @zezekim This was actually fixed in a previous update to the PHP API client, but we hadn't updated the dependency tree on AzuraRelay to include it. Should be fixed now. You will need to update any existing AzuraRelay setups before running the installer again.

**Comment by oyeandres** [comment]
@SlvrEagle23  First thank you very much for your response...

I already update the azurarelay but this error is present
"[ERROR] Base URL or API key is not specified. Please provide these values in" azurarelay.env "to continue!".

but i am thinking that i am typing the api wrong in Azurarelay.env
im typing api key that form. is it correct?
![image](https://user-images.githubusercontent.com/62250694/81473450-3e1e1d80-91c4-11ea-9092-47b2d6f872f2.png)

Thank you very much for your support and time

**Comment by jeremyn54** [comment]
I'm having a very similar problem at present, I was successfully able to setup a relay over a month ago but now this happens on a clean install. Is there a broken dependency somewhere?

>  AzuraCast Installation URL []:
> https://radio.wanderingsheep.net
> [30-Jul-2020 01:39:32 UTC] PHP Fatal error:  Uncaught TypeError: Argument 2 passed to AzuraCast\Api\Dto\RemoteDto::__construct() must be of the type int, null given, called in /var/azurarelay/www/vendor/azuracast/php-api-client/src/Dto/RemoteDto.php on line 108 and defined in /var/azurarelay/www/vendor/azuracast/php-api-client/src/Dto/RemoteDto.php:28
> Stack trace:
>#0 /var/azurarelay/www/vendor/azuracast/php-api-client/src/Dto/RemoteDto.php(108): AzuraCast\Api\Dto\RemoteDto->__construct()
>#1 /var/azurarelay/www/vendor/azuracast/php-api-client/src/Dto/StationDto.php(308): AzuraCast\Api\Dto\RemoteDto::fromArray()
>#2 /var/azurarelay/www/vendor/azuracast/php-api-client/src/Dto/NowPlayingDto.php(195): AzuraCast\Api\Dto\StationDto::fromArray()
>#3 /var/azurarelay/www/vendor/azuracast/php-api-client/src/Client.php(28): AzuraCast\Api\Dto\NowPlayingDto::fromArray()
>#4 /var/azurarelay/www/src/Console/Command/SetupCommand.php(35): AzuraCast\Api\Client->nowPlaying()
>#5 /var/azurarelay/www/vendor/symfony/console/Helper/QuestionHelper.php(470): App\Console\Command\Setu in /var/azurarelay/www/vendor/azuracast/php-api-client/src/Dto/RemoteDto.php on line 28
>Error: No such container:path: azurarelay_relay_1:/var/azurarelay/www_tmp/azurarelay.env

**Comment by epgshare01** [comment]
Same error here. My relay is broke. Any fixes?
